name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Hey
        run: |
          echo There
          exit 1
