name: First Workflow
on:
  - push


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo
        run: |
          echo "Hello World" 
          echo "Hello World 2" 
      - name: fail pelase
        run: exit 1


  parallel-job:
    runs-on: macos-latest
    steps:
      - name: Mac OS Cmd
        run: sw_vers

  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: Windows cmd
        run: ipconfig
