name: Working Dir and Shells
on:
  push:
    branches:
      - main
    
jobs:
  display-vd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display workinh wir
        run: |
          pwd
          ls -lhtr
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

  display-vd-windows:
    runs-on: windows-latest
    steps:
      - name: Display workinh wir
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
